name: Mt-KaHyPar CI

on: [ push, pull_request ]

jobs:
  mt_kahypar_tests:
    runs-on: ubuntu-20.04
    env:
      BOOST_ROOT : "/usr/local/share/boost/1.72.0"
      CI_ACTIVE : 1

    steps:
      - name: Checkout HEAD
        uses: actions/checkout@v2
        with:
         fetch-depth: 1

      - name: Install Dependencies
        run: |
          sudo apt-get install libtbb-dev libhwloc-dev libboost-program-options-dev lcov gcovr

      - name: Install Mt-KaHyPar Test Suite
        run: |
          git submodule init
          git submodule update
          rm -rf debug
          mkdir debug
          cd debug
          cmake .. -DCMAKE_BUILD_TYPE=DEBUG -DKAHYPAR_USE_GCOV=ON -DKAHYPAR_CI_BUILD=ON
          make -j2 mt_kahypar_tests;

      - name: Run Mt-KaHyPar Tests
        run: |
          cd debug
          ./tests/mt_kahypar_multilevel_tests;
          ./tests/mt_kahypar_nlevel_tests;
          ./tests/mt_kahypar_graph_tests;

      - name: Report Code Coverage
        run: |
          cd debug
          lcov --directory . --capture --output-file coverage.info;
          lcov --remove coverage.info '/usr/*' --output-file coverage.info;
          lcov --list coverage.info;
          gcovr -r ../ -x > report.xml;
          cd ..
          bash <(curl -s https://codecov.io/bash) || echo "Codecov did not collect coverage reports"

  mt_kahypar_integration:
    runs-on: ubuntu-20.04
    env:
      BOOST_ROOT : "/usr/local/share/boost/1.72.0"
      CI_ACTIVE : 1

    steps:
      - name: Checkout HEAD
        uses: actions/checkout@v2
        with:
         fetch-depth: 1

      - name: Install Dependencies
        run: |
          sudo apt-get install libtbb-dev libhwloc-dev libboost-program-options-dev lcov gcovr

      - name: Install Mt-KaHyPar Integration Tests
        run: |
          git submodule init
          git submodule update
          rm -rf build
          mkdir build
          cd build
          cmake .. -DCMAKE_BUILD_TYPE=RELEASE -DKAHYPAR_CI_BUILD=ON
          make -j2 MtKaHyPar
          make -j2 VerifyPartition

      - name: Run Mt-KaHyPar Integration Tests
        run: |
          ./tests/end_to_end/integration_tests.py

      - name: Run Mt-KaHyPar C Library Interface Tests
        run: |
          cd build
          make -j2 interface_test

      - name: Build Mt-KaHyPar Python Interface
        run: |
          cd build/python
          make -j2

      - name: Run Mt-KaHyPar Python Interface Tests
        run: |
          cd python/tests
          cp ../../build/python/mtkahyparhgp*.so mtkahyparhgp.so
          cp ../../build/python/mtkahypargp*.so mtkahypargp.so
          python3 test_mtkahyparhgp.py -v
          python3 test_mtkahypargp.py -v
